#Use the new container-based infrastructure
sudo: false

#Install some apt packages needed for spcomp
addons:
    apt_packages:
        - lib32stdc++6

#Set the build environment
env:
    - SMVERSION=1.7
    - SMVERSION=1.8

#Allow the experimental branch to fail
matrix:
  fast_finish: true
  allow_failures:
    - env: SMVERSION=1.8

#And compile!
install:
    - wget http://sourcemod.net/smdrop/$SMVERSION/ -O - | grep "\.tar\.gz" | sed 's/^.*"sourcemod/sourcemod/;s/\.tar\.gz".*$/.tar.gz/' | tail --lines=1 > sourcemod
    - wget --input-file=sourcemod --base=http://sourcemod.net/smdrop/$SMVERSION/
    - tar -xzf $(cat sourcemod)
before_script:
    - cd addons/sourcemod/scripting/
    - wget "http://www.doctormckay.com/download/scripting/include/morecolors.inc" -O include/morecolors.inc --no-check-certificate
    - wget "http://hg.limetech.org/projects/tf2items/tf2items_source/raw-file/tip/pawn/tf2items.inc" -O include/tf2items.inc
    - wget "https://code.limetech.org/diffusion/ST/browse/master/plugin/steamtools.inc?view=raw" -O include/steamtools.inc
    - chmod +x spcomp
    - mkdir compiled
script: ./compile.sh saxtonhale.sp

#Notifications
notifications:
    email: false
