#Use the new container-based infrastructure
sudo: false

#Install some apt packages needed for spcomp
addons:
    apt_packages:
        - lib32stdc++6

#Set the build environment
env:
  - SMVERSION=1.7 EASTER_BUNNY_BUILD=1
  - SMVERSION=1.8 EASTER_BUNNY_BUILD=1
  - SMVERSION=1.7 EASTER_BUNNY_BUILD=0
  - SMVERSION=1.8 EASTER_BUNNY_BUILD=0

#Allow the experimental branch to fail
matrix:
  fast_finish: true
  allow_failures:
    - env: SMVERSION=1.8 EASTER_BUNNY_BUILD=1
    - env: SMVERSION=1.8 EASTER_BUNNY_BUILD=0

#And compile!
before_script: chmod +x ./build.sh
script: ./build.sh

#Notifications
notifications:
    email: false
